development:
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  database: db/development.sqlite3
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  database: db/test.sqlite3
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  database: db/production.sqlite3
  pool: 5
  username: root
  password:
  host: localhost
