# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# You can use `rails secret` to generate a secure secret key.

development:
  secret_key_base: 67e4979539ce8540a1a0a70537c840d7d374b3093802205dddfcacfa819da3cbf77ac482d9ede02bbaf346a3f27b560475c57b2adab7428777c5ded21edb869c

test:
  secret_key_base: 9d06dd724f981ae0b0763e0a74614fd17a63a575908a6d492c4d24f84a12a61c7909997ce700a39ca6938af37ce007d285a1c9ca8f0fe80265afa199539f96ee

# K 9/21/16: make staging to be the same in every way possible
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
